DEBUG = True  # Turns on debugging features in Flask
PORT = 5000
SECRET_KEY = "Kugan49"
GEN_MENU={}
GEN_MENU[0] = {u"Accueil":u"/"}
GEN_MENU[1] = {u"T\xe9l\xe9chargements":u"SubMenuTitle"}
GEN_MENU[1][0] = {u"Fichiers":u"/gestionFichier/mnt/LOC/USB/DDL_OK/"}
GEN_MENU[1][1] = {u"JDownloader":u"/JD/"}
GEN_MENU[2] = {u"T\xe9l\xe9commande":u"SubMenuTitle"}
GEN_MENU[2][0] = {u"Kodi":u"/kodi/"}
GEN_MENU[2][1] = {u"Musique":u"/MPD/"}
GEN_MENU[3] = {u"Etat":u"SubMenuTitle"}
GEN_MENU[3][0] = {u"Statuts":u"/status/"}
GEN_MENU[3][1] = {u"log":u"/gestionFichier/log/home/osmc/tmp/"}
GEN_MENU[4] = {u"Avanc\xe9es":u"SubMenuTitle"}
GEN_MENU[4][0] = {u"Scripts":u"/gestionFichier/scripts/home/osmc/scripts/"}
GEN_MENU[4][1] = {u"SSH":u"/SSH/"}  
GEN_MENU[4][2] = {u"Config":u"/config/home/osmc/webosmc/config.py"}
GEN_MENU[5] = {u"Cloud":u"/ThrowBox/"}
LINK_AFF_MSG = True
LINK_MAJ_SITE = ["git", "pull"] #"sh /home/osmc/scripts/majWeb.sh"
LINK_VERIFMAJ = ["sh","/home/osmc/webosmc/verifVersion.sh"]#["git","-C /home/osmc/webosmc/ pull --dry-run 2>&1 | grep 'master' >/dev/null |echo $?"]
LINK_JDOWNLOADER = "https://my.jdownloader.org/?deviceId=4ad32ae65d600a9b070bba54a8f0429d#webinterface:downloads"
GESTIONFICHIER_DDL_PATH = "/mnt/LOC/USB"
GESTIONFICHIER_LST_EXCL_PATH = ['$RECYCLE.BIN','save', 'System Volume Information', 'test','install', 'musique', 'photos']
GESTIONFICHIER_LST_EXCL_FILES = ['.part','xyztetst']
SSH_PORT = 443
KODI_PORT = 8080
STATUS_CPUMIN=2
STATUS_LSTPROC={}
STATUS_LSTPROC[0] = {"Kodi":"kodi.bin"}
STATUS_LSTPROC[1] = {"JDownloader":"java"}
STATUS_LSTPROC[2] = {"Site web":"python"}
STATUS_LSTPROC[3] = {"MPD":"mpd"}
STATUS_LSTPROC[4] = {"Synchronisation":"unison"}
MPD_CONFIG="/home/osmc/webosmc/modules/MPD/MPD.ini"
THROWBOX_CONFIG="/home/osmc/webosmc/modules/ThrowBox/throwbox.ini"