DEBUG = True  # Turns on debugging features in Flask
PORT = 5000
SECRET_KEY = "Kugan49"
MENU={}
MENU[0] = {"Accueil":"/"}
MENU[1] = {"Fichiers":"/gestionFichier/mnt/LOC/USB/DDL_OK/"}
MENU[2] = {"Musique":"/MPD/"}
MENU[3] = {"Kodi":"/kodi/"}
MENU[4] = {"JDownloader":"/JD/"}
MENU[5] = {"SSH":"/SSH/"}  
MENU[6] = {"Config":"/config/"}
MENU[7] = {"test":"/test/"}
LINK_MAJ_SITE = "sh /home/osmc/scripts/majWeb.sh"
LINK_RECH_MAJ = '["git", "fetch --dry-run -v 2>&1 | grep "master" | grep "up" >/dev/null | echo $?"]'  				 
LINK_JDOWNLOADER = "https://my.jdownloader.org/?deviceId=4ad32ae65d600a9b070bba54a8f0429d#webinterface:downloads"
GESTIONFICHIER_DDL_PATH = "/mnt/LOC/USB"
GESTIONFICHIER_LST_EXCL_PATH = ['$RECYCLE.BIN','save', 'System Volume Information', 'test', 'musique', 'photos']
GESTIONFICHIER_LST_EXCL_FILES = ['.part','xyztetst']
MPD_CONFIG = "/modules/wymypy/wymypy.ini"
SSH_PORT = 4200
KODI_PORT = 8080